global:
  registry: k3d-bosun-registry:5000/amsors
  imagePullPolicy: Always

database:
  storageSize: 2Gi

agent:
  imagePullPolicy: Always
  idleScanInterval: 5s

auth:
  trustedProxyHeader: ""

ingress:
  enabled: false
  rateLimit:
    enabled: false

certManager:
  enabled: false
