---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bosun.io
  resources:
  - agentsessions
  - userenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bosun.io
  resources:
  - agentsessions/finalizers
  - userenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - bosun.io
  resources:
  - agentsessions/status
  - userenvironments/status
  verbs:
  - get
  - patch
  - update
