// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package db

import (
	"context"
)

const databaseHealth = `-- name: DatabaseHealth :one
SELECT 1::integer AS ok
`

func (q *Queries) DatabaseHealth(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, databaseHealth)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
