// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency_keys.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM bosun.idempotency_keys
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT user_id, key, method, path, request_hash, response_status, response_body, created_at, expires_at
FROM bosun.idempotency_keys
WHERE user_id = $1 AND key = $2 AND expires_at > now()
`

type GetIdempotencyKeyParams struct {
	UserID uuid.UUID `json:"user_id"`
	Key    string    `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (BosunIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Key)
	var i BosunIdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :execrows
INSERT INTO bosun.idempotency_keys (
    user_id, key, method, path, request_hash, response_status, response_body, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, key) DO UPDATE SET
    method = EXCLUDED.method,
    path = EXCLUDED.path,
    request_hash = EXCLUDED.request_hash,
    response_status = EXCLUDED.response_status,
    response_body = EXCLUDED.response_body,
    created_at = now(),
    expires_at = EXCLUDED.expires_at
WHERE bosun.idempotency_keys.expires_at <= now()
`

type InsertIdempotencyKeyParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Key            string    `json:"key"`
	Method         string    `json:"method"`
	Path           string    `json:"path"`
	RequestHash    []byte    `json:"request_hash"`
	ResponseStatus int32     `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
	ExpiresAt      time.Time `json:"expires_at"`
}

// InsertIdempotencyKey 在 advisory lock 保护下写入；已过期记录允许原子替换。
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.UserID,
		arg.Key,
		arg.Method,
		arg.Path,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
