// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type BosunIdempotencyKey struct {
	UserID         uuid.UUID `json:"user_id"`
	Key            string    `json:"key"`
	Method         string    `json:"method"`
	Path           string    `json:"path"`
	RequestHash    []byte    `json:"request_hash"`
	ResponseStatus int32     `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
	CreatedAt      time.Time `json:"created_at"`
	ExpiresAt      time.Time `json:"expires_at"`
}

type BosunRefreshToken struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	FamilyID   uuid.UUID  `json:"family_id"`
	TokenHash  []byte     `json:"token_hash"`
	IssuedAt   time.Time  `json:"issued_at"`
	ExpiresAt  time.Time  `json:"expires_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	ReplacedBy *uuid.UUID `json:"replaced_by"`
}

type BosunSession struct {
	ID                   uuid.UUID  `json:"id"`
	UserID               uuid.UUID  `json:"user_id"`
	CrNamespace          string     `json:"cr_namespace"`
	CrName               string     `json:"cr_name"`
	Tier                 string     `json:"tier"`
	Runtime              string     `json:"runtime"`
	ProviderMode         string     `json:"provider_mode"`
	ProviderCredentialID *uuid.UUID `json:"provider_credential_id"`
	StoragePolicy        string     `json:"storage_policy"`
	DesiredState         string     `json:"desired_state"`
	ResumeNonce          uuid.UUID  `json:"resume_nonce"`
	Phase                string     `json:"phase"`
	PhaseReason          string     `json:"phase_reason"`
	Conditions           []byte     `json:"conditions"`
	LastActiveAt         *time.Time `json:"last_active_at"`
	CrResourceVersion    int64      `json:"cr_resource_version"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
	DeletedAt            *time.Time `json:"deleted_at"`
	Version              int64      `json:"version"`
	DisplayName          string     `json:"display_name"`
	Priority             string     `json:"priority"`
}

type BosunSessionEvent struct {
	ID         uuid.UUID `json:"id"`
	SessionID  uuid.UUID `json:"session_id"`
	Type       string    `json:"type"`
	Payload    []byte    `json:"payload"`
	OccurredAt time.Time `json:"occurred_at"`
}

type BosunUser struct {
	ID           uuid.UUID  `json:"id"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	CreatedAt    time.Time  `json:"created_at"`
	DisabledAt   *time.Time `json:"disabled_at"`
}
