// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveSessionsForUser = `-- name: CountActiveSessionsForUser :one
SELECT count(*)
FROM bosun.sessions
WHERE user_id = $1
  AND deleted_at IS NULL
  AND phase IN ('Pending', 'Provisioning', 'Running', 'Idle', 'Hibernating', 'Restoring')
`

func (q *Queries) CountActiveSessionsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionsForUser = `-- name: CountSessionsForUser :one
SELECT count(*)
FROM bosun.sessions
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountSessionsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO bosun.sessions (
    id, user_id, cr_namespace, cr_name, tier, runtime, provider_mode,
    provider_credential_id, storage_policy, desired_state, resume_nonce,
    phase, phase_reason, conditions, last_active_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $16
)
RETURNING id, user_id, cr_namespace, cr_name, tier, runtime, provider_mode, provider_credential_id, storage_policy, desired_state, resume_nonce, phase, phase_reason, conditions, last_active_at, cr_resource_version, created_at, updated_at, deleted_at, version
`

type CreateSessionParams struct {
	ID                   uuid.UUID  `json:"id"`
	UserID               uuid.UUID  `json:"user_id"`
	CrNamespace          string     `json:"cr_namespace"`
	CrName               string     `json:"cr_name"`
	Tier                 string     `json:"tier"`
	Runtime              string     `json:"runtime"`
	ProviderMode         string     `json:"provider_mode"`
	ProviderCredentialID *uuid.UUID `json:"provider_credential_id"`
	StoragePolicy        string     `json:"storage_policy"`
	DesiredState         string     `json:"desired_state"`
	ResumeNonce          uuid.UUID  `json:"resume_nonce"`
	Phase                string     `json:"phase"`
	PhaseReason          string     `json:"phase_reason"`
	Conditions           []byte     `json:"conditions"`
	LastActiveAt         *time.Time `json:"last_active_at"`
	CreatedAt            time.Time  `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (BosunSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CrNamespace,
		arg.CrName,
		arg.Tier,
		arg.Runtime,
		arg.ProviderMode,
		arg.ProviderCredentialID,
		arg.StoragePolicy,
		arg.DesiredState,
		arg.ResumeNonce,
		arg.Phase,
		arg.PhaseReason,
		arg.Conditions,
		arg.LastActiveAt,
		arg.CreatedAt,
	)
	var i BosunSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CrNamespace,
		&i.CrName,
		&i.Tier,
		&i.Runtime,
		&i.ProviderMode,
		&i.ProviderCredentialID,
		&i.StoragePolicy,
		&i.DesiredState,
		&i.ResumeNonce,
		&i.Phase,
		&i.PhaseReason,
		&i.Conditions,
		&i.LastActiveAt,
		&i.CrResourceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getGatewaySessionIdentity = `-- name: GetGatewaySessionIdentity :one
SELECT id, cr_namespace, cr_name, phase, provider_mode
FROM bosun.sessions
WHERE cr_namespace = $1
  AND cr_name = $2
  AND deleted_at IS NULL
`

type GetGatewaySessionIdentityParams struct {
	CrNamespace string `json:"cr_namespace"`
	CrName      string `json:"cr_name"`
}

type GetGatewaySessionIdentityRow struct {
	ID           uuid.UUID `json:"id"`
	CrNamespace  string    `json:"cr_namespace"`
	CrName       string    `json:"cr_name"`
	Phase        string    `json:"phase"`
	ProviderMode string    `json:"provider_mode"`
}

func (q *Queries) GetGatewaySessionIdentity(ctx context.Context, arg GetGatewaySessionIdentityParams) (GetGatewaySessionIdentityRow, error) {
	row := q.db.QueryRow(ctx, getGatewaySessionIdentity, arg.CrNamespace, arg.CrName)
	var i GetGatewaySessionIdentityRow
	err := row.Scan(
		&i.ID,
		&i.CrNamespace,
		&i.CrName,
		&i.Phase,
		&i.ProviderMode,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, cr_namespace, cr_name, tier, runtime, provider_mode, provider_credential_id, storage_policy, desired_state, resume_nonce, phase, phase_reason, conditions, last_active_at, cr_resource_version, created_at, updated_at, deleted_at, version
FROM bosun.sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (BosunSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i BosunSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CrNamespace,
		&i.CrName,
		&i.Tier,
		&i.Runtime,
		&i.ProviderMode,
		&i.ProviderCredentialID,
		&i.StoragePolicy,
		&i.DesiredState,
		&i.ResumeNonce,
		&i.Phase,
		&i.PhaseReason,
		&i.Conditions,
		&i.LastActiveAt,
		&i.CrResourceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getSessionForUser = `-- name: GetSessionForUser :one
SELECT id, user_id, cr_namespace, cr_name, tier, runtime, provider_mode, provider_credential_id, storage_policy, desired_state, resume_nonce, phase, phase_reason, conditions, last_active_at, cr_resource_version, created_at, updated_at, deleted_at, version
FROM bosun.sessions
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetSessionForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSessionForUser(ctx context.Context, arg GetSessionForUserParams) (BosunSession, error) {
	row := q.db.QueryRow(ctx, getSessionForUser, arg.ID, arg.UserID)
	var i BosunSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CrNamespace,
		&i.CrName,
		&i.Tier,
		&i.Runtime,
		&i.ProviderMode,
		&i.ProviderCredentialID,
		&i.StoragePolicy,
		&i.DesiredState,
		&i.ResumeNonce,
		&i.Phase,
		&i.PhaseReason,
		&i.Conditions,
		&i.LastActiveAt,
		&i.CrResourceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertSessionEvent = `-- name: InsertSessionEvent :exec
INSERT INTO bosun.session_events (id, session_id, type, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSessionEventParams struct {
	ID         uuid.UUID `json:"id"`
	SessionID  uuid.UUID `json:"session_id"`
	Type       string    `json:"type"`
	Payload    []byte    `json:"payload"`
	OccurredAt time.Time `json:"occurred_at"`
}

func (q *Queries) InsertSessionEvent(ctx context.Context, arg InsertSessionEventParams) error {
	_, err := q.db.Exec(ctx, insertSessionEvent,
		arg.ID,
		arg.SessionID,
		arg.Type,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const listDeletingSessions = `-- name: ListDeletingSessions :many
SELECT id, user_id, cr_namespace, cr_name, tier, runtime, provider_mode, provider_credential_id, storage_policy, desired_state, resume_nonce, phase, phase_reason, conditions, last_active_at, cr_resource_version, created_at, updated_at, deleted_at, version
FROM bosun.sessions
WHERE deleted_at IS NOT NULL AND phase_reason <> 'CleanupComplete'
ORDER BY deleted_at
LIMIT $1
`

func (q *Queries) ListDeletingSessions(ctx context.Context, limit int32) ([]BosunSession, error) {
	rows, err := q.db.Query(ctx, listDeletingSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BosunSession{}
	for rows.Next() {
		var i BosunSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CrNamespace,
			&i.CrName,
			&i.Tier,
			&i.Runtime,
			&i.ProviderMode,
			&i.ProviderCredentialID,
			&i.StoragePolicy,
			&i.DesiredState,
			&i.ResumeNonce,
			&i.Phase,
			&i.PhaseReason,
			&i.Conditions,
			&i.LastActiveAt,
			&i.CrResourceVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSessions = `-- name: ListPendingSessions :many
SELECT id, user_id, cr_namespace, cr_name, tier, runtime, provider_mode, provider_credential_id, storage_policy, desired_state, resume_nonce, phase, phase_reason, conditions, last_active_at, cr_resource_version, created_at, updated_at, deleted_at, version
FROM bosun.sessions
WHERE deleted_at IS NULL AND phase = 'Pending'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListPendingSessions(ctx context.Context, limit int32) ([]BosunSession, error) {
	rows, err := q.db.Query(ctx, listPendingSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BosunSession{}
	for rows.Next() {
		var i BosunSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CrNamespace,
			&i.CrName,
			&i.Tier,
			&i.Runtime,
			&i.ProviderMode,
			&i.ProviderCredentialID,
			&i.StoragePolicy,
			&i.DesiredState,
			&i.ResumeNonce,
			&i.Phase,
			&i.PhaseReason,
			&i.Conditions,
			&i.LastActiveAt,
			&i.CrResourceVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT id, user_id, cr_namespace, cr_name, tier, runtime, provider_mode, provider_credential_id, storage_policy, desired_state, resume_nonce, phase, phase_reason, conditions, last_active_at, cr_resource_version, created_at, updated_at, deleted_at, version
FROM bosun.sessions
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListSessionsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]BosunSession, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BosunSession{}
	for rows.Next() {
		var i BosunSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CrNamespace,
			&i.CrName,
			&i.Tier,
			&i.Runtime,
			&i.ProviderMode,
			&i.ProviderCredentialID,
			&i.StoragePolicy,
			&i.DesiredState,
			&i.ResumeNonce,
			&i.Phase,
			&i.PhaseReason,
			&i.Conditions,
			&i.LastActiveAt,
			&i.CrResourceVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionCleanupComplete = `-- name: MarkSessionCleanupComplete :execrows
UPDATE bosun.sessions
SET phase_reason = 'CleanupComplete',
    updated_at = $2,
    version = version + 1
WHERE id = $1 AND deleted_at IS NOT NULL AND phase_reason <> 'CleanupComplete'
`

type MarkSessionCleanupCompleteParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) MarkSessionCleanupComplete(ctx context.Context, arg MarkSessionCleanupCompleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionCleanupComplete, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const projectSessionStatus = `-- name: ProjectSessionStatus :one
UPDATE bosun.sessions
SET phase = $2,
    phase_reason = $3,
    conditions = $4,
    last_active_at = $5,
    cr_resource_version = $6,
    updated_at = $7,
    version = version + 1
WHERE id = $1 AND cr_resource_version < $6
RETURNING id, user_id, cr_namespace, cr_name, tier, runtime, provider_mode, provider_credential_id, storage_policy, desired_state, resume_nonce, phase, phase_reason, conditions, last_active_at, cr_resource_version, created_at, updated_at, deleted_at, version
`

type ProjectSessionStatusParams struct {
	ID                uuid.UUID  `json:"id"`
	Phase             string     `json:"phase"`
	PhaseReason       string     `json:"phase_reason"`
	Conditions        []byte     `json:"conditions"`
	LastActiveAt      *time.Time `json:"last_active_at"`
	CrResourceVersion int64      `json:"cr_resource_version"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

func (q *Queries) ProjectSessionStatus(ctx context.Context, arg ProjectSessionStatusParams) (BosunSession, error) {
	row := q.db.QueryRow(ctx, projectSessionStatus,
		arg.ID,
		arg.Phase,
		arg.PhaseReason,
		arg.Conditions,
		arg.LastActiveAt,
		arg.CrResourceVersion,
		arg.UpdatedAt,
	)
	var i BosunSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CrNamespace,
		&i.CrName,
		&i.Tier,
		&i.Runtime,
		&i.ProviderMode,
		&i.ProviderCredentialID,
		&i.StoragePolicy,
		&i.DesiredState,
		&i.ResumeNonce,
		&i.Phase,
		&i.PhaseReason,
		&i.Conditions,
		&i.LastActiveAt,
		&i.CrResourceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const softDeleteSession = `-- name: SoftDeleteSession :one
UPDATE bosun.sessions
SET desired_state = 'Hibernated',
    phase = 'Deleting',
    phase_reason = 'DeleteRequested',
    deleted_at = $3,
    updated_at = $3,
    version = version + 1
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, cr_namespace, cr_name, tier, runtime, provider_mode, provider_credential_id, storage_policy, desired_state, resume_nonce, phase, phase_reason, conditions, last_active_at, cr_resource_version, created_at, updated_at, deleted_at, version
`

type SoftDeleteSessionParams struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	DeletedAt *time.Time `json:"deleted_at"`
}

func (q *Queries) SoftDeleteSession(ctx context.Context, arg SoftDeleteSessionParams) (BosunSession, error) {
	row := q.db.QueryRow(ctx, softDeleteSession, arg.ID, arg.UserID, arg.DeletedAt)
	var i BosunSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CrNamespace,
		&i.CrName,
		&i.Tier,
		&i.Runtime,
		&i.ProviderMode,
		&i.ProviderCredentialID,
		&i.StoragePolicy,
		&i.DesiredState,
		&i.ResumeNonce,
		&i.Phase,
		&i.PhaseReason,
		&i.Conditions,
		&i.LastActiveAt,
		&i.CrResourceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const updateSessionDesiredState = `-- name: UpdateSessionDesiredState :one
UPDATE bosun.sessions
SET desired_state = $3,
    resume_nonce = $4,
    last_active_at = $5,
    updated_at = $6,
    version = version + 1
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL AND version = $7
RETURNING id, user_id, cr_namespace, cr_name, tier, runtime, provider_mode, provider_credential_id, storage_policy, desired_state, resume_nonce, phase, phase_reason, conditions, last_active_at, cr_resource_version, created_at, updated_at, deleted_at, version
`

type UpdateSessionDesiredStateParams struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	DesiredState string     `json:"desired_state"`
	ResumeNonce  uuid.UUID  `json:"resume_nonce"`
	LastActiveAt *time.Time `json:"last_active_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	Version      int64      `json:"version"`
}

func (q *Queries) UpdateSessionDesiredState(ctx context.Context, arg UpdateSessionDesiredStateParams) (BosunSession, error) {
	row := q.db.QueryRow(ctx, updateSessionDesiredState,
		arg.ID,
		arg.UserID,
		arg.DesiredState,
		arg.ResumeNonce,
		arg.LastActiveAt,
		arg.UpdatedAt,
		arg.Version,
	)
	var i BosunSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CrNamespace,
		&i.CrName,
		&i.Tier,
		&i.Runtime,
		&i.ProviderMode,
		&i.ProviderCredentialID,
		&i.StoragePolicy,
		&i.DesiredState,
		&i.ResumeNonce,
		&i.Phase,
		&i.PhaseReason,
		&i.Conditions,
		&i.LastActiveAt,
		&i.CrResourceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}
